name: linters

on:
  push:
    branches: [main]
    tags: v*
  pull_request:

jobs:
  run_linters:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run style:check